$me = "Luis Morales"
$title = " - Grades Report `n"

# Fill the arrays from file
$file = Get-Content "C:\Users\luise\OneDrive\School\CISA 3309 - Scripting Languages\Assignments\posh\student_data.dat"
$line = $null;
[String[]] $studentName = @();
[float[]] $assignment1 = @();
[float[]] $assignment2 = @();
[float[]] $assignment3 = @();
[float[]] $assignment4 = @();
[float[]] $midTermExam = @();
[float[]] $finalExam = @();
[float[]] $grade = @();
[char[]] $letterGrade = @();

#$line = $null;
        foreach ($line in $file)
        {
         #Split fields into values
         $line = $line -split (",")
         $modelName += $line[0];
         $price += $line[1];
         $onHand += $line[2];
		 $studentName += $line[0];
		 $assignment1 += $line[1];
		 $assignment2 += $line[2];
		 $assignment3 += $line[3];
		 $assignment4 += $line[4];
		 $midTermExam += $line[5];
		 $finalExam += $line[6];
#		 $grade = @();
		}

[int]$aChar = 0;
[int]$bChar = 0;
[int]$cChar = 0;
[int]$dChar = 0;
[int]$fChar = 0;
  

# === User Input ===
$courseName = Read-Host "Enter course name: ";
# ==================

$title = " - Grades Report `n"
Write-Host `n $("{0,39} {1,0}{2,0}" -f  "",$courseName, $title)
#             FullName  As1   As2    As3     As4   Mid   Final  Grade  LetGrade 
Write-Host $("{0, -20} {1,7} {2,12} {3,12} {4,12} {5,12} {6,11} {7,6} {8,12}" -f "Full Name", "Assignment-1", "Assignment-2", "Assignment-3", "Assignment-4", "Mid Term Exam", "Final Exam", "Grade", "Letter Grade")
Write-Host $("{0, -20} {1,7} {2,12} {3,12} {4,12} {5,12} {6,11} {7,6} {8,12}" -f "------------------", "------------", "------------", "------------", "------------", "-------------", "----------", "------", "-------------")
  for ($nextItem =0 ; $nextItem -lt $studentName.length; $nextItem++)
      {
       $val1n = $studentName[$nextItem]
       $val2n = $assignment1[$nextItem]
       $val3n = $assignment2[$nextItem]
       $val4n = $assignment3[$nextItem]
       $val5n = $assignment4[$nextItem]
       $val6n = $midTermExam[$nextItem]
       $val7n = $finalExam[$nextItem]
       $val8n = ((($assignment1[$nextItem] + $assignment2[$nextItem])*.05) + (($assignment3[$nextItem] + $assignment4[$nextItem])*.10) + ($midTermExam[$nextItem]*.30) + ($finalExam[$nextItem]*.40))
                
       # assign letter grades
       if ($val8n -le 59.4){$val9n = "F"}
       elseif ($val8n -le 69.4){$val9n = "D"}
       elseif ($val8n -le 79.4){$val9n = "C"}
       elseif ($val8n -le 89.4){$val9n = "B"}
       elseif ($val8n -ge 89.5){$val9n = "A"}

       # count letter grades
       if ($val9n -eq "A"){$aChar++}
       if ($val9n -eq "B"){$bChar++}
       if ($val9n -eq "C"){$cChar++}
       if ($val9n -eq "D"){$dChar++}
       if ($val9n -eq "F"){$fChar++}
                            
#      FullName   As1       As2      As3        As4       Mid      Final     Grade    LetGrade                                    
       Write-Host $("{0, -20} {1,7:f2} {2,12:f2} {3,12:f2} {4,12:f2} {5,12:f2} {6,15:f2} {7,8:f2} {8,8:f2}" -f $val1n,$val2n,$val3n,$val4n,$val5n,$val6n,$val7n,$val8n,$val9n)
      }
Write-Host "-----------------------------------------------------------------------------------------------------------------------"

$tot1 = $assignment1 | Measure-Object -Sum | Select-Object -ExpandProperty Sum
$tot2 = $assignment2 | Measure-Object -Sum | Select-Object -ExpandProperty Sum
$tot3 = $assignment3 | Measure-Object -Sum | Select-Object -ExpandProperty Sum
$tot4 = $assignment4 | Measure-Object -Sum | Select-Object -ExpandProperty Sum
$tot5 = $midTermExam | Measure-Object -Sum | Select-Object -ExpandProperty Sum
$tot6 = $finalExam | Measure-Object -Sum | Select-Object -ExpandProperty Sum
$tot7 = $grade | Measure-Object -Sum | Select-Object -ExpandProperty Sum
$avg1 = ($tot1)/$assignment1.Length
$avg2 = ($tot2)/$assignment2.Length
$avg3 = ($tot3)/$assignment3.Length
$avg4 = ($tot4)/$assignment4.Length
$avg5 = ($tot5)/$midTermExam.Length
$avg6 = ($tot6)/$finalExam.Length
$avg7 = ($tot7)/$grade.Length

Write-Host $("{0, -20} {1,7:f2} {2,12:f2} {3,12:f2} {4,12:f2} {5,12:f2} {6,15:f2} {7,8:f2} " -f "Class Averages: ", $avg1,$avg2,$avg3,$avg4,$avg5,$avg6,$avg7)
Write-Host "-----------------------------------------------------------------------------------------------------------------------"

# Footer
$now = Get-Date -Format "dddd MMMM'/'dd'/'yyyy HH:mm:ss"
Write-Host "Grades by group: A's: $aChar, B's: $bChar, C's: $cChar, D's: $dChar, F's: $fChar"
Write-Host "Report Generated By: $me @$now"
exit