echo "========================================"
echo "Spring 2023 - Bash Assignment 01"
echo "Developer : Luis Morales"
echo "Running on : " $(date)
echo "========================================"
echo "          *"
echo "         ***"
echo "        *****"
echo "       *******"
echo "      ******************"
echo "                *******"
echo "                 *****"
echo "                  ***"
echo "                   *"